# This is a basic workflow to help you get started with Actions

name: flutterBuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    - name: Flutter Install
      run: git clone https://github.com/flutter/flutter.git
    - run: echo "::add-path::$(pwd)/flutter/bin"
    - run: flutter channel dev
    - run: flutter upgrade
    - run: flutter pub get
    
    - name: sshpass install
      run: sudo apt-get upgrade
    - run: sudo apt-get install sshpass
    
    - name: build apk
      run: flutter build apk --target-platform android-arm64
    
    - name: upload apk
      run: sshpass -p ${{ secrets.SOURCEFORGE_PASS }} rsync -avP -e ssh -v build/app/outputs/flutter-apk/app-release.apk lawrathod@frs.sourceforge.net:/home/frs/project/dndr/app/dndr.apk
    








